SET IDENTITY_INSERT [dbo].[Equipo] ON
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (1, N'A         ', N'Rusia')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (2, N'A', N'Arabia Saudita')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (3, N'A', N'Egipto')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (4, N'A', N'Uruguay')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (5, N'B', N'Portugal')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (6, N'B', N'España')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (7, N'B', N'Marruecos')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (8, N'B', N'Iran')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (9, N'C', N'Francia')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (10, N'C', N'Australia')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (11, N'C', N'Peru')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (12, N'C', N'Dinamarca')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (13, N'D', N'Argentina')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (14, N'D', N'Islandia')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (15, N'D', N'Croacia')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (16, N'D', N'Nigeria')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (17, N'E', N'Brasil')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (18, N'E', N'Suiza')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (19, N'E', N'Costa Rica')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (20, N'E', N'Serbia')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (21, N'F', N'Alemania')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (22, N'F', N'México')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (23, N'F', N'Suecia')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (24, N'F', N'Corea del Sur')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (25, N'G', N'Belgica')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (26, N'G', N'Panama')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (27, N'G', N'Túnez')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (28, N'G', N'Inglaterra')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (29, N'H', N'Polonia')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (30, N'H', N'Senegal')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (31, N'H', N'Colombia')
INSERT INTO [dbo].[Equipo] ([idEquipo], [Grupo], [nombreEquipo]) VALUES (32, N'H', N'Japón')
SET IDENTITY_INSERT [dbo].[Equipo] OFF
