//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departamento()
        {
            this.Empleado2 = new HashSet<Empleado>();
        }
    
        public int departamentoID { get; set; }
        public string nombre { get; set; }
        public Nullable<int> jefeID { get; set; }
        public Nullable<int> representanteID { get; set; }
        public string ubicacion { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Empleado Empleado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado> Empleado2 { get; set; }
    }
}
