//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado_Departamento
    {
        public int departamentoID { get; set; }
        public int jefeID { get; set; }
        public int representanteID { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Empleado Empleado1 { get; set; }
    }
}
