//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Empleado_Departamento = new HashSet<Empleado_Departamento>();
            this.Empleado_Departamento1 = new HashSet<Empleado_Departamento>();
            this.Empleado1 = new HashSet<Empleado>();
        }
    
        public int empleadoID { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<int> jerarquia { get; set; }
        public Nullable<int> jefeInmediatoID { get; set; }
        public string puesto { get; set; }
        public Nullable<int> departamento { get; set; }
        public Nullable<int> sede { get; set; }
        public string fotoURL { get; set; }
        public string numero { get; set; }
        public string mail { get; set; }
    
        public virtual Departamento Departamento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado_Departamento> Empleado_Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado_Departamento> Empleado_Departamento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado> Empleado1 { get; set; }
        public virtual Empleado Empleado2 { get; set; }
        public virtual Sede Sede1 { get; set; }
    }
}
